#!/bin/sh
mkdir -p target
sh build-deps.sh
rm -f ./target/bin_c_run
gcc -Ideps/base64/include -Ideps/yyjson/src -I/usr/include/ -O2 -Ideps/cJSON -L/opt/homebrew/lib -I/opt/homebrew/include/ main.c -o target/bin_c_run -lgmp target/cJSON.o target/libbase64.o -lm -lpcre2-8 -lpthread target/yyjson.o
../xtime.rb ./target/bin_c_run ../run.js "$@"
