#!/bin/sh
sh deps.sh
rm -f ./bin_cpp_run
g++ -Ibase64/include -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/lib -I/opt/homebrew/include/ -O3 -std=c++20 -Isimdjson simdjson/simdjson.o base64/lib/libbase64.o main.cpp -o ./bin_cpp_run -lgmp -lre2 -lpthread
./bin_cpp_run ../run.txt "$@"
