#!/bin/sh
sh deps.sh
rm -f ./bin_cpp_test
g++ -Ibase64/include -Wl,-rpath,/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/opt/llvm/lib/c++ -L/opt/homebrew/lib -I/opt/homebrew/include/ -std=c++20 -Isimdjson simdjson/simdjson.o base64/lib/libbase64.o main.cpp -o ./bin_cpp_test -lgmp -lre2 -lpthread
./bin_cpp_test ../test.txt "$@"
