#!/bin/sh
rm -f ./target/java-benchmarks-1.0-SNAPSHOT.jar
mvn compile package -Pjava-optimized -DskipTests -Dmaven.test.skip=true -q
../xtime.rb java -server -jar ./target/java-benchmarks-1.0-SNAPSHOT.jar ../run.js $@
